version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: uts_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - NILAI=80,85,90,95
    volumes:
      - ./output:/app/output
    command: python uts.py

volumes:
  db_data: